[greeter]
background=/usr/share/backgrounds/glassxfce/silver-wave.png
user-background=false
theme-name=WhiteSur-Dark
icon-theme-name=WhiteSur
font-name=Inter 10
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format=%a %d %b  %H:%M
position=50%,center 50%,center
