#!/bin/sh
set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --architectures amd64 \
  --binary-image iso-hybrid \
  --chroot-squashfs-compression-type xz \
  --bootloaders "grub-efi syslinux" \
  --uefi-secure-boot enable \
  --debian-installer live \
  --debian-installer-gui true \
  --archive-areas "main contrib non-free-firmware" \
  --security true \
  --updates true \
  --apt-recommends false \
  --apt-indices false \
  --image-name glassxfce \
  --iso-volume "GLASSXFCE" \
  --iso-application "GlassXFCE Live" \
  --iso-publisher "Unofficial Debian derivative" \
  --bootappend-live "boot=live components quiet splash vt.handoff=7 loglevel=3 systemd.show_status=false rd.systemd.show_status=false udev.log_level=3 vt.global_cursor_default=0 plymouth.ignore-serial-consoles username=live hostname=glassxfce" \
  "${@}"
