backend = "glx";
vsync = true;
use-damage = true;

shadow = true;
shadow-radius = 22;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.28;

corner-radius = 14;

blur: {
  method = "dual_kawase";
  strength = 5;
};

animations = (
  {
    triggers = [ "open", "show" ];
    preset = "appear";
    duration = 0.16;
    scale = 0.96;
  },
  {
    triggers = [ "close", "hide" ];
    preset = "disappear";
    duration = 0.14;
    scale = 0.96;
  }
);

rules = (
  {
    match = "class_g = 'Xfdesktop' && window_type != 'desktop'";
    blur-background = false;
    opacity = 1.0;
    shadow = true;
    corner-radius = 10;
  },
  {
    match = "window_type = 'menu' || window_type = 'dropdown_menu' || window_type = 'popup_menu' || window_type = 'tooltip' || window_type = 'combo'";
    blur-background = false;
    opacity = 1.0;
    shadow = true;
    corner-radius = 10;
  },
  {
    match = "fullscreen";
    corner-radius = 0;
  },
  {
    match = "window_type = 'desktop'";
    shadow = false;
    corner-radius = 0;
  },
  {
    match = "window_type = 'dock'";
    shadow = true;
    blur-background = true;
  },
  {
    match = "class_g = 'Rofi'";
    blur-background = true;
    corner-radius = 18;
  },
  {
    match = "window_type = 'notification'";
    blur-background = true;
    shadow = true;
    corner-radius = 16;
  }
);
