backend = "xrender";
vsync = true;
use-damage = true;

shadow = true;
shadow-radius = 18;
shadow-offset-x = -6;
shadow-offset-y = -6;
shadow-opacity = 0.24;

corner-radius = 12;
fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;

rules = (
  { match = "fullscreen"; corner-radius = 0; },
  { match = "window_type = 'desktop'"; shadow = false; corner-radius = 0; },
  { match = "window_type = 'dock'"; shadow = true; }
);
